[package]
name = "find_first_word"
version = "0.1.0"
authors = ["Andrew Nikolayenko <nikolayenko.andrew@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
